nelmio_api_doc:
    documentation:
        info:
            title: Bilemo
            description: So great items, and all
            version: 1.0.0
        paths:
            /api/login_check:
                post:
                    operationId: postCredentialsItem
                    tags:
                        - Token
                    summary: permet d'obtenir le token JWT pour se logger.
                    requestBody:
                        description: Crée un nouveau token JWT
                        content:
                            application/json:
                                schema:
                                    $ref: '#/components/schemas/Credentials'
                    responses:
                        '200':
                            description: Récupère le token JWT
                            content:
                                application/json:
                                    schema:
                                        $ref: '#/components/schemas/Token'
            /api/customers:
                get:
                    summary: récupérer une liste de client.es
                post:
                    summary: créer un.e client.e
                    requestBody:
                        content:
                            application/json:
                                schema:
                                    $ref: '#/components/schemas/Customer'
            /api/customers/{id}:
                get:
                    summary: récupérer un.e client.e
                put:
                    summary: modifier un.e client.e
                delete:
                    summary: supprimer un.e client.e
            /api/items:
                get:
                    summary: récupérer tous les produits
            /api/items/{id}:
                get:
                    summary: récupérer un produit

        components:
            schemas:
                Token:
                    type: object
                    properties:
                        token:
                            type: string
                            readOnly: true
                Credentials:
                    type: object
                    properties:
                        username:
                            type: string
                            default: platform-1@mail.com
                        password:
                            type: string
                            default: password
                Customer:
                    type: object
                    properties:
                        firstName:
                            type: string
                        name:
                            type: string
                        email:
                            type: string
                        postCode:
                            type: string
                        gender:
                            type: string
                        age:
                            type: int

            securitySchemes:
                bearerAuth:
                    type: apiKey
                    in: header
                    name: Authorization
        security:
            - bearerAuth: []
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
